In [84]:
import numpy as np
import pandas as pd

In [85]:
np.__version__

'1.23.2'

In [86]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv -O hw-1.csv

--2022-09-11 16:59:26--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘hw-1.csv’

hw-1.csv            100%[===================>]   1.41M  4.00MB/s    in 0.4s    

2022-09-11 16:59:27 (4.00 MB/s) - ‘hw-1.csv’ saved [1475504/1475504]



In [87]:
df = pd.read_csv('hw-1.csv')

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [89]:
df.Make.value_counts(dropna=False)

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [90]:
df[df.Make=='Audi'].Model.value_counts(dropna=False).count()

34

In [91]:
out=df.isnull().sum()
print(out)
num=0
for i in range(out.count()):
    if out[i] != 0:
        num+=1
print(num)
print((out != 0).sum())

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64
5
5


In [92]:
((df.isnull().sum())!=0).sum()

5

In [93]:
df["Engine Cylinders"].median()

6.0

In [94]:
mode=df["Engine Cylinders"].mode()
mode

0    4.0
Name: Engine Cylinders, dtype: float64

In [95]:
df["Engine Cylinders"].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [96]:
df["Engine Cylinders"].fillna(mode)

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [98]:
df["Engine Cylinders"].median()

6.0

In [99]:
df_L = df[df.Make == "Lotus"]
df_L = df_L[["Engine HP", "Engine Cylinders"]]
df_L = df_L.drop_duplicates()

In [100]:
df_L.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9 entries, 3912 to 4293
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Engine HP         9 non-null      float64
 1   Engine Cylinders  9 non-null      float64
dtypes: float64(2)
memory usage: 216.0 bytes


In [106]:
X = df_L.values
print(X)
XTX = X.T.dot(X)
print(XTX)
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[189.   4.]
 [218.   4.]
 [217.   4.]
 [350.   8.]
 [400.   6.]
 [276.   6.]
 [345.   6.]
 [257.   4.]
 [240.   4.]]
[[7.31684e+05 1.34100e+04]
 [1.34100e+04 2.52000e+02]]
[[ 5.53084235e-05 -2.94319825e-03]
 [-2.94319825e-03  1.60588447e-01]]


In [111]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
w = XTX_inv.dot(X.T).dot(y)
w[0]

4.594944810094551